#google_analytics: G-96PH5VNT48
theme: jekyll-theme-cayman
show_downloads: true

github:
  zip_url: https://github.com/ariel-waisman/LabelsToROis/archive/master.zip
  tar_url: https://github.com/ariel-waisman/LabelsToROis/tarball/master
